"""add_user_model_and_order_relation.

Revision ID: 79d92d41897d
Revises: 002
Create Date: 2026-03-11 17:32:28.310628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79d92d41897d'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('openid', sa.String(length=50), nullable=False),
    sa.Column('unionid', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unionid')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.drop_index(op.f('ix_product_option_values_option_id'), table_name='product_option_values')
    op.drop_table('product_option_values')
    op.drop_index(op.f('ix_product_options_product_id'), table_name='product_options')
    op.drop_table('product_options')
    op.drop_index(op.f('ix_order_item_options_order_item_id'), table_name='order_item_options')
    op.drop_table('order_item_options')
    op.drop_constraint(op.f('merchants_username_key'), 'merchants', type_='unique')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.add_column('orders', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('orders_order_number_key'), 'orders', type_='unique')
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('orders', 'user_id')
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_unique_constraint(op.f('merchants_username_key'), 'merchants', ['username'], postgresql_nulls_not_distinct=False)
    op.create_table('order_item_options',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('order_item_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('option_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('option_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('extra_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('order_item_options_order_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('order_item_options_pkey'))
    )
    op.create_index(op.f('ix_order_item_options_order_item_id'), 'order_item_options', ['order_item_id'], unique=False)
    op.create_table('product_options',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_multiple', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_options_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_options_pkey'))
    )
    op.create_index(op.f('ix_product_options_product_id'), 'product_options', ['product_id'], unique=False)
    op.create_table('product_option_values',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('extra_price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['product_options.id'], name=op.f('product_option_values_option_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_option_values_pkey'))
    )
    op.create_index(op.f('ix_product_option_values_option_id'), 'product_option_values', ['option_id'], unique=False)
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
