"""add_order_source_and_merchant_operator.

Revision ID: b721e9e117e6
Revises: ae83f5747aab
Create Date: 2026-03-12 12:11:39.448114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b721e9e117e6'
down_revision: Union[str, None] = 'ae83f5747aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('source_type', sa.String(length=20), nullable=False, server_default='customer'))
    op.add_column('orders', sa.Column('merchant_operator_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'orders', 'merchants', ['merchant_operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'merchant_operator_id')
    op.drop_column('orders', 'source_type')
    # ### end Alembic commands ###
